<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>LaporanProduktivitasWPF</RootNamespace>
    <AssemblyName>LaporanProduktivitasAdmin</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <StartupObject>LaporanProduktivitasWPF.App</StartupObject>
  </PropertyGroup>

</Project>
